name: AliyunAutoReply

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    env:
      VERSION: v1.0.1
      # 使用你提供的公网地址
      ALIYUN_REGISTRY: crpi-x68pqc6t5zexwzms.cn-guangzhou.personal.cr.aliyuncs.com
      # 完整的镜像名称（包含命名空间和仓库名）
      FULL_IMAGE_NAME: crpi-x68pqc6t5zexwzms.cn-guangzhou.personal.cr.aliyuncs.com/xianyuauto/xianyu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Debug - Show image info
        run: |
          echo "Registry: ${{ env.ALIYUN_REGISTRY }}"
          echo "Full Image Name: ${{ env.FULL_IMAGE_NAME }}"
          echo "Version: ${{ env.VERSION }}"
          
      - name: Login to Aliyun Personal Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        
      - name: Build and push multi-arch image
        run: |
          # 构建并推送多架构镜像（一次性完成）
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ env.FULL_IMAGE_NAME }}:${{ env.VERSION }} \
            -t ${{ env.FULL_IMAGE_NAME }}:latest \
            -f Dockerfile . \
            --push
            
      - name: Verify image pushed successfully
        run: |
          echo "构建完成，请检查阿里云镜像仓库"
          echo "镜像地址: ${{ env.FULL_IMAGE_NAME }}:${{ env.VERSION }}"
          echo "最新标签: ${{ env.FULL_IMAGE_NAME }}:latest"
